// src/data/verbs.ts
export interface VerbItem {
  en: string;
  de: string[];
  note?: string;
}

export const VERBS: VerbItem[] = [
  // Core demo verbs
  { en: "to be", de: ["sein"], note: "irregular" },
  { en: "to have", de: ["haben"], note: "irregular" },
  { en: "to go", de: ["gehen"], note: "irregular" },
  { en: "to come", de: ["kommen"], note: "irregular" },
  { en: "to make / do", de: ["machen", "tun"], note: "machen is default" },
  { en: "to say", de: ["sagen"], note: "regular" },
  { en: "to see", de: ["sehen"], note: "irregular (e→ie)" },
  { en: "to take", de: ["nehmen"], note: "irregular (e→i)" },
  { en: "to give", de: ["geben"], note: "irregular (e→i)" },
  { en: "to want", de: ["wollen"], note: "modal" },
  {
    en: "to can / be able to",
    de: ["können", "koennen"],
    note: "modal; accept oe",
  },
  {
    en: "to must / have to",
    de: ["müssen", "muessen"],
    note: "modal; accept ue",
  },
  { en: "to should / ought to", de: ["sollen"], note: "modal" },
  {
    en: "to may / be allowed to",
    de: ["dürfen", "duerfen"],
    note: "modal; accept ue",
  },
  { en: "to like (to)", de: ["mögen", "moegen"], note: "modal-like" },
  { en: "to learn", de: ["lernen"], note: "regular" },
  { en: "to read", de: ["lesen"], note: "irregular (e→ie)" },
  { en: "to write", de: ["schreiben"], note: "regular" },
  { en: "to eat", de: ["essen"], note: "irregular (e→i)" },
  { en: "to drink", de: ["trinken"], note: "regular" },
  {
    en: "to live / reside",
    de: ["wohnen", "leben"],
    note: "wohnen=reside, leben=be alive",
  },
  { en: "to work", de: ["arbeiten"], note: "regular" },
  { en: "to speak", de: ["sprechen"], note: "irregular (e→i)" },
  { en: "to understand", de: ["verstehen"], note: "regular" },
  {
    en: "to begin / start",
    de: ["anfangen", "beginnen"],
    note: "anfangen is separable",
  },
  {
    en: "to stop / quit",
    de: ["aufhören", "aufhoeren", "stoppen"],
    note: "aufhören is common",
  },

  // Extended verbs (sample ~70 more, mix of common A1–B1 verbs)
  { en: "to run", de: ["laufen"], note: "irregular (au→äu)" },
  { en: "to sleep", de: ["schlafen"], note: "irregular (a→ä)" },
  { en: "to drive / travel", de: ["fahren"], note: "irregular (a→ä)" },
  { en: "to buy", de: ["kaufen"], note: "regular" },
  { en: "to sell", de: ["verkaufen"], note: "regular" },
  { en: "to bring", de: ["bringen"], note: "mixed" },
  { en: "to think", de: ["denken"], note: "irregular (dachte)" },
  { en: "to believe", de: ["glauben"], note: "regular" },
  { en: "to know (fact)", de: ["wissen"], note: "irregular" },
  { en: "to know (be acquainted)", de: ["kennen"], note: "irregular (kannte)" },
  { en: "to wait", de: ["warten"], note: "regular" },
  { en: "to need", de: ["brauchen"], note: "regular" },
  { en: "to use", de: ["benutzen"], note: "regular" },
  { en: "to play", de: ["spielen"], note: "regular" },
  { en: "to dance", de: ["tanzen"], note: "regular" },
  { en: "to drive", de: ["fahren"], note: "irregular" },
  { en: "to fly", de: ["fliegen"], note: "irregular" },
  {
    en: "to walk",
    de: ["spazieren", "gehen spazieren"],
    note: "common phrase",
  },
  { en: "to swim", de: ["schwimmen"], note: "irregular" },
  { en: "to help", de: ["helfen"], note: "irregular (e→i)" },
  { en: "to hold", de: ["halten"], note: "irregular (a→ä)" },
  { en: "to carry", de: ["tragen"], note: "irregular (a→ä)" },
  { en: "to call", de: ["rufen"], note: "irregular" },
  { en: "to answer", de: ["antworten"], note: "regular" },
  { en: "to ask", de: ["fragen"], note: "regular" },
  { en: "to open", de: ["öffnen", "oeffnen"], note: "regular" },
  { en: "to close", de: ["schließen", "schliessen"], note: "irregular" },
  { en: "to put / place", de: ["stellen"], note: "regular" },
  { en: "to sit", de: ["sitzen"], note: "irregular" },
  { en: "to stand", de: ["stehen"], note: "irregular" },
  { en: "to lie (position)", de: ["liegen"], note: "irregular" },
  { en: "to lay (down something)", de: ["legen"], note: "regular" },
  { en: "to sleep", de: ["schlafen"], note: "irregular" },
  { en: "to dream", de: ["träumen", "traeumen"], note: "regular" },
  { en: "to cook", de: ["kochen"], note: "regular" },
  { en: "to bake", de: ["backen"], note: "irregular" },
  { en: "to wash", de: ["waschen"], note: "irregular (a→ä)" },
  { en: "to clean", de: ["putzen"], note: "regular" },
  { en: "to shower", de: ["duschen"], note: "regular" },
  { en: "to brush (teeth)", de: ["putzen (Zähne)"], note: "phrase" },
  { en: "to get / receive", de: ["bekommen"], note: "irregular" },
  { en: "to find", de: ["finden"], note: "irregular" },
  { en: "to lose", de: ["verlieren"], note: "irregular" },
  { en: "to win", de: ["gewinnen"], note: "irregular" },
  { en: "to build", de: ["bauen"], note: "regular" },
  { en: "to break", de: ["brechen"], note: "irregular (e→i)" },
  { en: "to cut", de: ["schneiden"], note: "irregular" },
  { en: "to draw", de: ["zeichnen"], note: "regular" },
  { en: "to paint", de: ["malen"], note: "regular" },
  { en: "to sing", de: ["singen"], note: "irregular" },
  { en: "to dance", de: ["tanzen"], note: "regular" },
  { en: "to laugh", de: ["lachen"], note: "regular" },
  { en: "to cry", de: ["weinen"], note: "regular" },
  { en: "to love", de: ["lieben"], note: "regular" },
  { en: "to hate", de: ["hassen"], note: "regular" },
  { en: "to hope", de: ["hoffen"], note: "regular" },
  { en: "to wait for", de: ["warten auf"], note: "prepositional" },
  { en: "to explain", de: ["erklären", "erklaeren"], note: "regular" },
  { en: "to tell / narrate", de: ["erzählen", "erzaehlen"], note: "regular" },
  { en: "to mean", de: ["meinen"], note: "regular" },
  { en: "to remember", de: ["sich erinnern"], note: "reflexive" },
  { en: "to forget", de: ["vergessen"], note: "irregular (e→i)" },
  { en: "to try", de: ["versuchen"], note: "regular" },
  { en: "to practice", de: ["üben", "ueben"], note: "regular" },
  { en: "to move (house)", de: ["umziehen"], note: "separable" },
  { en: "to arrive", de: ["ankommen"], note: "separable" },
  { en: "to depart / leave", de: ["abfahren"], note: "separable" },
  { en: "to enter", de: ["eintreten"], note: "separable" },
  { en: "to exit / get out", de: ["aussteigen"], note: "separable" },
  { en: "to change", de: ["ändern", "aendern"], note: "regular" },
  { en: "to stay", de: ["bleiben"], note: "irregular" },
  { en: "to send", de: ["schicken"], note: "regular" },
  { en: "to receive (mail)", de: ["empfangen"], note: "irregular (a→ä)" },
  { en: "to cost", de: ["kosten"], note: "regular" },
  { en: "to pay", de: ["bezahlen"], note: "regular" },
  { en: "to save (money)", de: ["sparen"], note: "regular" },
  { en: "to spend (money)", de: ["ausgeben"], note: "irregular, separable" },
  { en: "to spend (time)", de: ["verbringen"], note: "irregular" },
  { en: "to happen", de: ["passieren"], note: "regular" },
  { en: "to work out / function", de: ["klappen"], note: "regular" },
  { en: "to succeed", de: ["gelingen"], note: "irregular" },
  { en: "to fail", de: ["scheitern"], note: "regular" },
  { en: "to prepare", de: ["vorbereiten"], note: "separable" },
  { en: "to plan", de: ["planen"], note: "regular" },
  { en: "to organize", de: ["organisieren"], note: "regular" },
  { en: "to travel", de: ["reisen"], note: "regular" },
  { en: "to visit", de: ["besuchen"], note: "regular" },
  {
    en: "to stay overnight",
    de: ["übernachten", "uebernachten"],
    note: "regular",
  },
  { en: "to order", de: ["bestellen"], note: "regular" },
  { en: "to cook", de: ["kochen"], note: "regular" },
  { en: "to taste", de: ["schmecken"], note: "regular" },
  { en: "to invite", de: ["einladen"], note: "irregular (a→ä), separable" },
  { en: "to celebrate", de: ["feiern"], note: "regular" },
  { en: "to marry", de: ["heiraten"], note: "regular" },
  { en: "to die", de: ["sterben"], note: "irregular (e→i)" },
];
